#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define TRANSITION_TIME 0.5

#define KICK_STRENGTH_Y 350
#define KICK_STRENGTH_X 10

#define FOOTBALL_COLLISION_BITMASK 0x0000001
#define GROUND_COLLISION_BITMASK 0x0000002

#define SCORE_FONT_SIZE 0.05
#define TITLE_FONT_SIZE 0.1
#define GAME_OVER_FONT_SIZE 0.07

#endif // __DEFINITIONS_H__
